go get -u -v github.com/BurntSushi/toml 
go get -u -v github.com/Joker/jade  
go get -u -v github.com/Shopify/goreferrer 
go get -u -v github.com/aymerick/raymond 
go get -u -v github.com/davecgh/go-spew  
go get -u -v github.com/denisenkom/go-mssqldb 
go get -u -v github.com/eknkc/amber 
go get -u -v github.com/fatih/structs  
go get -u -v github.com/flosch/pongo2 
go get -u -v github.com/go-sql-driver/mysql  
go get -u -v github.com/gomodule/redigo 
go get -u -v github.com/gorilla/schema  
go get -u -v github.com/iris-contrib/blackfriday 
go get -u -v github.com/iris-contrib/formBinder v5.0.0+ 
go get -u -v github.com/iris-contrib/go.uuid 
go get -u -v github.com/json-iterator/go  
go get -u -v github.com/kataras/golog 
go get -u -v github.com/kataras/iris v11.1.1+
go get -u -v github.com/kataras/pio 
go get -u -v github.com/microcosm-cc/bluemonday  
go get -u -v github.com/pmezard/go-difflib  
go get -u -v github.com/russross/blackfriday 
go get -u -v github.com/ryanuber/columnize 
go get -u -v github.com/satori/go.uuid  
go get -u -v github.com/shurcooL/sanitized_anchor_name  
go get -u -v github.com/valyala/fasthttp  
go get -u -v go.uber.org/atomic  
go get -u -v go.uber.org/multierr  
go get -u -v go.uber.org/zap  
go get -u -v golang.org/x/net 
go get -u -v gopkg.in/natefinch/lumberjack.v2 
go get -u -v gopkg.in/yaml.v2 